name: Deploy Dev
run-name: ${{ github.actor }} is deploying dev branch
on:
  # push:
  #   branches:
  #     - "dev"
  workflow_run:
    workflows: ['Prepare Deployment for all branches']
    types: [completed]
    branches: [dev]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'only for dev'
      - run: date
