name: Deploy Test
run-name: ${{ github.actor }} is deploying test branch
on:
  # push:
  #   branches:
  #     - "test"
  workflow_run:
    workflows: ['Prepare Deployment for all branches']
    types: [completed]
    branches: [test]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'only for dev'
      - run: date
